# Generated by Django 4.2.1 on 2023-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=55, verbose_name='Название KZ')),
                ('name_ru', models.CharField(max_length=55, verbose_name='Название RU')),
                ('test_type', models.CharField(choices=[('NIS', 'NIS')], max_length=10, verbose_name='Тип Теста')),
                ('order', models.IntegerField(verbose_name='Очередь')),
                ('duration', models.IntegerField(verbose_name='Длительность в минутах')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lessons/')),
            ],
            options={
                'db_table': 'lesson',
                'unique_together': {('test_type', 'order')},
            },
        ),
    ]
