# Generated by Django 4.2.1 on 2023-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('NIS', 'NIS')], max_length=10, verbose_name='Тип Теста')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('language', models.CharField(choices=[('KZ', 'KZ'), ('RU', 'RU')], max_length=2, verbose_name='Язык варианта')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='variants/')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'db_table': 'variant',
                'ordering': ['id'],
                'unique_together': {('test_type', 'name')},
            },
        ),
    ]
