# Generated by Django 4.2.1 on 2023-05-14 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_variant_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('point', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VariantQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Очередь')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_questions', to='quiz.lesson', verbose_name='Предмет')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_questions', to='quiz.question', verbose_name='Предмет')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_questions', to='quiz.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Вопросы варианта',
                'verbose_name_plural': 'Вопросы варианта',
                'db_table': 'variant_questions',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['variant', 'lesson', 'question'], name='variant_que_variant_a4972b_idx')],
                'unique_together': {('lesson', 'question'), ('variant', 'lesson', 'question', 'order')},
            },
        ),
    ]
