# Generated by Django 4.2.1 on 2023-05-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_variant_created_variant_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantquestions',
            options={'ordering': ['variant', 'lesson', 'order'], 'verbose_name': 'Вопросы варианта', 'verbose_name_plural': 'Вопросы варианта'},
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=1, verbose_name='Балл'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('order', models.IntegerField(verbose_name='Очередь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'answer',
                'ordering': ['order'],
            },
        ),
    ]
