# Generated by Django 4.2.1 on 2023-05-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_variantquestions_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='variantquestions',
            options={'ordering': ['variant', 'order'], 'verbose_name': 'Вопросы варианта', 'verbose_name_plural': 'Вопросы варианта'},
        ),
        migrations.RemoveIndex(
            model_name='variantquestions',
            name='variant_que_variant_a4972b_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_questions', to='quiz.lesson', verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='variantquestions',
            unique_together={('variant', 'question')},
        ),
        migrations.AddIndex(
            model_name='variantquestions',
            index=models.Index(fields=['variant', 'question'], name='variant_que_variant_54c41b_idx'),
        ),
        migrations.RemoveField(
            model_name='variantquestions',
            name='lesson',
        ),
    ]
