# Generated by Django 4.2.1 on 2023-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='question',
            name='correct_way',
            field=models.TextField(null=True, verbose_name='Объяснение'),
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.TextField(null=True, verbose_name='Ссылка'),
        ),
    ]
