# Generated by Django 4.2.1 on 2023-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_testtype_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность в минутах'),
        ),
    ]
