# Generated by Django 4.2.1 on 2023-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_testtype_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtypelesson',
            name='has_by_lesson',
        ),
        migrations.AddField(
            model_name='testtype',
            name='has_by_lesson',
            field=models.BooleanField(default=False, verbose_name='По очереди'),
        ),
    ]
