# Generated by Django 4.2.1 on 2023-05-26 12:31

import core.constants.AnswerChoices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_testtypelesson_has_by_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(choices=[('CHOICE', 'CHOICE'), ('MULTICHOICE', 'MULTICHOICE')], default=core.constants.AnswerChoices.ANSWER_CHOICES['CHOICE'], max_length=12, verbose_name='Тип Ответа'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='name',
            field=models.CharField(choices=[('NIS', 'NIS'), ('KTL', 'KTL')], max_length=10, unique=True, verbose_name='Тип Теста'),
        ),
    ]
